# Copyright 2021 Gregory Chadwick <mail@gregchadwick.co.uk>
# Licensed under the Apache License Version 2.0, with LLVM Exceptions, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

PROG_NAME = hello_world

include ../../build-flow/Makefile.include
