# Copyright 2021 Gregory Chadwick <mail@gregchadwick.co.uk>
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

PROG_NAME = hello_world

include ../../build-flow/Makefile.include
